on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lerna-package-bumps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: get lerna changes
      run: |
        echo "::set-output name=lerna_changed_packages::$(yarn --silent run lerna changed --json)"
      id: lerna_changes
    - run: |
        echo `yarn --silent run lerna changed --json | jq '[.[] | "- [`\(.name)`](\(.location)): v\(.version)"] | join("\\n") | @sh "::set-output name=lerna_bumps::\(.)"' --raw-output`
      id: lerna_bumps
