on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lerna-package-bumps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: get lerna changes
      run: >
        output=$(yarn --silent run lerna changed --json | jq '[.[] | "- [`\(.name)`](\(.location)): v\(.version)"] | join("\\n") | @sh "::set-output name=lerna_bumps::\(.)"' --raw-output);
        echo "::debug file=app.js,line=1::$output";
        echo "$output";
      id: lerna_bumps
