on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lerna-package-bumps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: get lerna changes
      shell: bash
      run: |
        sh get-lerna-changes.sh
      id: lerna_bumps
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: 36
        body: ${{ steps.lerna_bumps.outputs.lerna_bumps }}
